[package]
name = "celestium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
mc-varint = { version = "0.1.1"}
dotenv = "0.15.0"
